<meta charset="utf-8">
<meta name="keywords" content="<?php if(isset($_GET['argc']) && isset($meta["{$_GET['argc']}.keywords"])) echo $meta["{$_GET['argc']}.keywords"]; elseif(isset($_GET['argb']) && isset($meta["{$_GET['argb']}.keywords"])) echo $meta["{$_GET['argb']}.keywords"]; elseif(isset($_GET['arga']) && isset($meta["{$_GET['arga']}.keywords"])) echo $meta["{$_GET['arga']}.keywords"]; ?><?=Meta::getMetaFromPage("keywords"); ?>">
<meta name="description" content="<?php if(isset($_GET['argc']) && isset($meta["{$_GET['argc']}.description"])) echo $meta["{$_GET['argc']}.description"]; elseif(isset($_GET['argb']) && isset($meta["{$_GET['argb']}.description"])) echo $meta["{$_GET['argb']}.description"]; elseif(isset($_GET['arga']) && isset($meta["{$_GET['arga']}.description"])) echo $meta["{$_GET['arga']}.description"]; ?><?=Meta::getMetaFromPage("description"); ?>">
<meta property="og:title" content="<?php if(isset($_GET['arga']) && isset($meta["{$_GET['arga']}.title"])) echo $meta["{$_GET['arga']}.title"]." | "; ?><?=Meta::getMetaFromPage("title"); ?><?=$meta["site.title"]?>" />
<meta property="og:type" content="website" />
<meta property="og:url" content="http://<?php if(isset($meta["site.url"])) echo $meta["site.url"]; ?><?php echo '/'.$lang2; ?><?php if(isset($_GET['page']) && $_GET['page']!='index') echo '/'.$_GET['page']; ?><?php if(isset($_GET['arga'])) echo '/'.$_GET['arga']; ?><?php if(isset($_GET['argb'])) echo '/'.$_GET['argb']; ?><?php if(isset($_GET['argc'])) echo '/'.$_GET['argc']; ?>" />
<meta property="og:description" content="<?php if(isset($_GET['argc']) && isset($meta["{$_GET['argc']}.description"])) echo $meta["{$_GET['argc']}.description"]; elseif(isset($_GET['argb']) && isset($meta["{$_GET['argb']}.description"])) echo $meta["{$_GET['argb']}.description"]; elseif(isset($_GET['arga']) && isset($meta["{$_GET['arga']}.description"])) echo $meta["{$_GET['arga']}.description"]; ?><?=Meta::getMetaFromPage("description"); ?>" />
<meta property="og:site_name" content="<?php if(isset($meta["site.title"])) echo $meta["site.title"]?>" />
<meta property="og:image" content="" />
<meta property="og:locale" content="<?php echo $lang2; ?>_CA" />
<title><?php if(isset($_GET['argc']) && isset($meta["{$_GET['argc']}.title"])) echo $meta["{$_GET['argc']}.title"]." | "; ?><?php if(isset($_GET['argb']) && isset($meta["{$_GET['argb']}.title"])) echo $meta["{$_GET['argb']}.title"]." | "; ?><?php if(isset($_GET['arga']) && isset($meta["{$_GET['arga']}.title"])) echo $meta["{$_GET['arga']}.title"]." | "; ?><?=Meta::getMetaFromPage("title"); ?><?php if(isset($meta["site.title"])) echo $meta["site.title"]; ?></title>
